sudo: false 

language: node_js

node_js:
- node 

script:
- npm run test

notifications:
  email:
    recipients:
     - mateusz.banaszak5303@gmail.com
  # slack: examinationgroup:FuqgTJO8oBOSwG6LPy3jyczZ