sudo: false 

language: node_js

node_js:
- node 

script:
- npm build
- npm run test

notifications:  
  email:  
    recipients:  
    - mateusz.banaszak5303@gmail.com
    - andreeaandreea99@yahoo.com
    
    on_success: always  
    on_failure: always
  slack: examinationgroup:FuqgTJO8oBOSwG6LPy3jyczZ